apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azurefile-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: azurefile # This storage class comes with AKS cluster running on nodes that accept Premium Storage Disk (like DS2_v2)